services:
  - type: web
    name: venom-kazino
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: ADMIN_GIFT_USERNAME
        sync: false
      - key: WITHDRAW_FEE_PERCENT
        value: 8
